name: My First workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "My First github action run"

      - name: List all files
        run: ls

      - name: read file
        run: cat README.md